</main>
<footer>

    <section>
        <h5>Navegación</h5>

        <ul>
            <li><a href="home">Inicio</a></li>
            <li><a href="login">Inicio de sesión</a></li>
            <li><a href="register">Registrarse</a></li>
        </ul>
    </section>
    <section>
        <h5>Listas</h5>

        <ul>
            <li><a href="list/chapters">Capítulos</a></li>
            <li><a href="list/seasons">Temporadas</a></li>
            <li><a href="list/cast">Elenco</a></li>
        </ul>
    </section>
    <section>
        <h5>Repositorio</h5>

        <ul>
            <li><a href="https://github.com/LukaSaldivia/web-simuladores">GitHub</a></li>

        </ul>
    </section>


</footer>
<svg style="display:none;">

<defs>
    <filter id="noise">
        <feTurbulence baseFrequency="0.99 0.0" numOctaves="9" seed="0" type="fractalNoise">
            <animate attributeName="seed" values="0;50" dur="40ms" repeatCount="indefinite"/>
        </feTurbulence>            
        <feDisplacementMap in="SourceGraphic" scale="100">

        </feDisplacementMap>
        
    </filter>
</defs>

</svg>
  
</body>
</html>