</main>
<footer>

    <section>
        <h5>Links</h5>

        <ul>
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li><a href="#">Link 4</a></li>
            <li><a href="#">Link 5</a></li>
        </ul>
    </section>
    <section>
        <h5>Recursos</h5>

        <ul>
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li><a href="#">Link 4</a></li>
            <li><a href="#">Link 5</a></li>
        </ul>
    </section>
    <section>
        <h5>Navegación</h5>

        <ul>
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li><a href="#">Link 4</a></li>
            <li><a href="#">Link 5</a></li>
        </ul>
    </section>

</footer>
<svg style="display:none;">

<defs>
    <filter id="noise">
        <feTurbulence baseFrequency="0.99 0.0" numOctaves="9" seed="0" type="fractalNoise">
            <animate attributeName="seed" values="0;50" dur="40ms" repeatCount="indefinite"/>
        </feTurbulence>            
        <feDisplacementMap in="SourceGraphic" scale="100">

        </feDisplacementMap>
        
    </filter>
</defs>

</svg>
  
</body>
</html>