<?php 
  require './templates/header.phtml'
?>

<h2>Iniciar sesión</h2>

<form action="auth-login" method="post">
  <div class="row">
    <label for="username">Usuario</label>
    <input name="username" id="username" type="text">
  </div>
  <div class="row">
    <label for="password">Contraseña</label>
    <input name="password" id="password" type="password">
  </div>
  <div class="row">
    <input type="submit" value="Iniciar Sesión">
  </div>

  <div class="row">
    <p>¿No tienes una cuenta? <a href="register">Regístrate ahora</a></p>
    
  </div>
</form>

<div class="error">
  <p><?= $error ?></p>
</div>


<?php 
  require './templates/footer.phtml'
?>