<?php 
  require './templates/header.phtml'
?>

<h2>Registro</h2>

<form action="auth-register" method="post">
  <div class="row">
    <label for="username">Usuario</label>
    <input name="username" id="username" type="text">
  </div>
  <div class="row">
    <label for="password">Contraseña</label>
    <input name="password" id="password" type="password">
  </div>
  <div class="row">
    <input type="submit" value="Registrarse">
  </div>

  <div class="row">
    <p>¿Ya tienes una cuenta? <a href="login">Inicie sesión</a></p>
    
  </div>
</form>

<div class="error">
  <p><?= $error ?></p>
</div>


<?php 
  require './templates/footer.phtml'
?>