<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./public/css/general.css">
    <script defer src="./public/js/header.js"></script>
    <title>Los Simuladores</title>
</head>

<body>

<header>
    <a href="home" class="home">Inicio</a>

    <ul>
        <li><a href="temporadas">Temporadas</a></li>
        <li><a href="login">Iniciar Sesión</a></li>
    </ul>
</header>
<main>
