<?php 
  require './templates/header.phtml';
?>

<div class="landing">
  <header>
    <h1>Los Simuladores</h1>
    <h5>Recopilación de todo el contenido disponible en YouTube <img class="icon" aria-hidden="true" src="./public/src/icons/youtube.png" alt="Ícono de Youtube"></h5>
  </header>

  <div class="img-container">
    <img src="./public/src/img/simuladores-bustos.png" alt="Silueta de Los Simuladores">
  </div>
</div>


<?php 
  require './templates/footer.phtml';
?>
