<?php 
  require './templates/header.phtml';
?>

<div class="landing">
  <header>
    <h1>Los Simuladores</h1>
    <h5>Recopilación de todo el contenido disponible en <span>Youtube</span></h5>
  </header>

  <div class="img-container">
    <img src="./public/src/img/simuladores-bustos.png" alt="Silueta de Los Simuladores">
  </div>
</div>


<div class="videos-container">
  <?php foreach($caps as $cap): ?>

    <a href="view/<?= $cap->idcap ?>" class="card">
    <img src="https://img.youtube.com/vi/<?= $cap->idcap ?>/hqdefault.jpg" alt="<?= $cap->nombrecap ?>">
    <div class="details">
      <h5><?= $cap->nombrecap ?></h5>
      <small><?= $cap->nombretemp ?></small>
    </div>
    </a>


  <?php endforeach ?>
</div>


<?php 
  require './templates/footer.phtml';
?>
