<?php 
  require './templates/header.phtml';
?>

<div class="landing">
  <header>
    <h1>Los Simuladores</h1>
    <h5>Recopilación de todo el contenido disponible en <span>Youtube</span></h5>
  </header>

  <div class="img-container">
    <img src="./public/src/img/simuladores-bustos.png" alt="Silueta de Los Simuladores">
  </div>
</div>



<?php 
  require './templates/footer.phtml';
?>
