<?php 
  require './templates/header.phtml';
?>



<ul class="items">
  <?php foreach($caps as $cap): ?>
    <li>
      <a href="view/<?= $cap->idcap ?>">
      <span class="season"><?=$cap->nombretemp?></span></a>
      <?php if(isset($_SESSION['USER_ID'])) :?>
        <section class="actions">
        <a href="delete/chapter/<?= $cap->idtemp ?>">Eliminar</a>
        <a href="edit/chapter/<?= $cap->idtemp ?>">Editar</a>
        </section>
        <?php endif ?>
    </li>
  <?php endforeach ?>
  <a href="add/seasons">Agregar una temporada</a>


</ul>

<?php 
  require './templates/footer.phtml';
?>
